name = "Wayland_protocols_jll"
uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
version = "1.18.0+3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Wayland_jll = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
